//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeMY.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDersler
    {

        [Display(Name = "Ders Id: ")]
        public int DersId { get; set; }

        [Display(Name = "User Id: ")]
        public int UserId { get; set; }

        [Display(Name = "Ders Adý: ")]
        public string DersAdi { get; set; }

        [Display(Name = "1. Sýnav Puaný: ")]
        [Range(0, 100, ErrorMessage = "Please enter correct value.")]
        public Nullable<double> Sinav1 { get; set; }

        [Display(Name = "2. Sýnav Puaný: ")]
        public Nullable<double> Sinav2 { get; set; }

        [Display(Name = "3. Sýnav Puaný: ")]
        public Nullable<double> Sinav3 { get; set; }

        [Display(Name = "Ortalama: ")]
        public Nullable<double> Ortalama { get; set; }

        [Display(Name = "Baþarý Durumu: ")]
        public string Basari { get; set; }

        [Display(Name = "User: ")]
        public virtual User User { get; set; }
    }
}

